// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel VisualizeUV

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<float4> UVMap;

[numthreads(8,8,1)]
void VisualizeUV (uint3 id : SV_DispatchThreadID)
{
    // TODO: insert actual code here!
    
    UVMap[id.xy] = float4(id.x / 1024.0f,id.y/1024.0f, 0, 0);
    //Result[id.xy] = float4(0,0,0,1);
}
